FROM node:16-alpine

# Set the working directory and fix ownership
WORKDIR /app
# RUN chown -R node:node /app

# Switch to `node` user
# USER node

# Install dependencies
COPY ./package.json ./
RUN npm install


# Copy remaining files
COPY . .

RUN chmod -R 777 ./node_modules

# Start the application
CMD ["npm", "run", "start"]