name: Deploy Multi-Container Docker Project

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # build test image (for client project)
            - name: Build Test Image for Client Project
              run: docker build -t phinguyen/complex-react-client-test -f ./client/Dockerfile.dev ./client

            # use test image to run tests (for client project)
            - name: Run Tests for Client Project
              run: docker run -e CI=true phinguyen/complex-react-client-test npm test -- --coverage
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            # build production images for services in parallel
            - name: Build Production Docker Image for Client
              run: docker build -t phinguyen/complex-client ./client

            - name: Build Production Docker Image for Nginx
              run: docker build -t phinguyen/complex-nginx ./nginx

            - name: Build Production Docker Image for Server
              run: docker build -t phinguyen/complex-server ./server

            - name: Build Production Docker Image for Worker
              run: docker build -t phinguyen/complex-worker ./worker