name: Deploy Multi-Container Docker Project

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # build test image (for client project)
            - name: Build Test Image for Client Project
              run: docker build -t nguyenhongphi2807/complex-react-client-test -f ./client/Dockerfile.dev ./client

            # use test image to run tests (for client project)
            - name: Run Tests for Client Project
              run: docker run -e CI=true nguyenhongphi2807/complex-react-client-test npm test -- --coverage
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            # build production images for services in parallel
            - name: Build Production Docker Images for services
              run: |
                docker build -t nguyenhongphi2807/complex-client ./client
                docker build -t nguyenhongphi2807/complex-nginx ./nginx
                docker build -t nguyenhongphi2807/complex-server ./server
                docker build -t nguyenhongphi2807/complex-worker ./worker

            - name: Login to Docker Hub using Docker CLI & Github Action Secrets
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

            - name: Push Production Docker Images into Docker Hub
              run: |
                docker push nguyenhongphi2807/complex-client
                docker push nguyenhongphi2807/complex-nginx
                docker push nguyenhongphi2807/complex-server
                docker push nguyenhongphi2807/complex-worker
